CREATE TABLE IF NOT EXISTS TelecomDataTable 
(
`id` INT NOT NULL AUTO_INCREMENT,
`Bearer Id` INT DEFAULT NULL, 
`Start` TEXT DEFAULT NULL,
`Start ms` INT DEFAULT NULL,
`End` TEXT DEFAULT NULL, 
`End ms` INT DEFAULT NULL, 
`Dur. (ms)` INT DEFAULT NULL, 
`IMSI` INT DEFAULT NULL,
`MSISDN/Number` INT DEFAULT NULL, 
`IMEI` INT DEFAULT NULL, 
`Last Location Name` INT DEFAULT NULL, 
`Avg RTT DL (ms)` INT DEFAULT NULL,
`Avg RTT UL (ms)` INT DEFAULT NULL, 
`Avg Bearer TP DL (kbps)` INT DEFAULT NULL, 
`Avg Bearer TP UL (kbps)` INT DEFAULT NULL,
`TCP DL Retrans. Vol (Bytes)` INT DEFAULT NULL, 
`TCP UL Retrans. Vol (Bytes)` INT DEFAULT NULL,
`DL TP < 50 Kbps (%)` INT DEFAULT NULL, 
`50 Kbps < DL TP < 250 Kbps (%)` INT DEFAULT NULL,
`250 Kbps < DL TP < 1 Mbps (%)` INT DEFAULT NULL, 
`DL TP > 1 Mbps (%)` INT DEFAULT NULL,
`UL TP < 10 Kbps (%)` INT DEFAULT NULL, 
`10 Kbps < UL TP < 50 Kbps (%)` INT DEFAULT NULL,
`50 Kbps < UL TP < 300 Kbps (%)` INT DEFAULT NULL, 
`UL TP > 300 Kbps (%)` INT DEFAULT NULL,
`HTTP DL (Bytes)` INT DEFAULT NULL, 
`HTTP UL (Bytes)` INT DEFAULT NULL, 
`Activity Duration DL (ms)` INT DEFAULT NULL,
`Activity Duration UL (ms)` INT DEFAULT NULL, 
`Dur. (ms).1` INT DEFAULT NULL, 
`Handset Manufacturer` TEXT DEFAULT NULL,
`Handset Type` TEXT DEFAULT NULL, 
`Nb of sec with 125000B < Vol DL` INT DEFAULT NULL,
`Nb of sec with 1250B < Vol UL < 6250B` INT DEFAULT NULL,
`Nb of sec with 31250B < Vol DL < 125000B` INT DEFAULT NULL,
`Nb of sec with 37500B < Vol UL` INT DEFAULT NULL,
`Nb of sec with 6250B < Vol DL < 31250B` INT DEFAULT NULL,
`Nb of sec with 6250B < Vol UL < 37500B` INT DEFAULT NULL,
`Nb of sec with Vol DL < 6250B` INT DEFAULT NULL, 
`Nb of sec with Vol UL < 1250B` INT DEFAULT NULL,
`Social Media DL (Bytes)` INT DEFAULT NULL, 
`Social Media UL (Bytes)` INT DEFAULT NULL,
`Google DL (Bytes)` INT DEFAULT NULL, 
`Google UL (Bytes)` INT DEFAULT NULL, 
`Email DL (Bytes)` INT DEFAULT NULL,
`Email UL (Bytes)` INT DEFAULT NULL, 
`Youtube DL (Bytes)` INT DEFAULT NULL, 
`Youtube UL (Bytes)` INT DEFAULT NULL,
`Netflix DL (Bytes)` INT DEFAULT NULL, 
`Netflix UL (Bytes)` INT DEFAULT NULL, 
`Gaming DL (Bytes)` INT DEFAULT NULL,
`Gaming UL (Bytes)` INT DEFAULT NULL, 
`Other DL (Bytes)` INT DEFAULT NULL, 
`Other UL (Bytes)` INT DEFAULT NULL,
`Total UL (Bytes)` INT DEFAULT NULL, 
`Total DL (Bytes)` INT DEFAULT NULL, 
PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
