CREATE TABLE IF NOT EXISTS TelecomDataTable 
(
`id` INT NOT NULL AUTO_INCREMENT,
`Gaming DL (Bytes)` INT DEFAULT NULL,
`Gaming UL (Bytes)` INT DEFAULT NULL, 
`Other DL (Bytes)` INT DEFAULT NULL, 
`Other UL (Bytes)` INT DEFAULT NULL,
`Total UL (Bytes)` INT DEFAULT NULL, 
`Total DL (Bytes)` INT DEFAULT NULL, 
PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;
