CREATE TABLE IF NOT EXISTS TelecomDataTable 
(
`id` INT NOT NULL AUTO_INCREMENT,
`Bearer Id` INT DEFAULT NULL, 
`Dur. (ms)` INT DEFAULT NULL, 
`IMSI` INT DEFAULT NULL,
`MSISDN/Number` INT DEFAULT NULL, 
`IMEI` INT DEFAULT NULL, 
`Last Location Name` INT DEFAULT NULL, 
`Avg RTT DL (ms)` INT DEFAULT NULL,
`Avg RTT UL (ms)` INT DEFAULT NULL, 
`Avg Bearer TP DL (kbps)` INT DEFAULT NULL, 
`Avg Bearer TP UL (kbps)` INT DEFAULT NULL,
`TCP DL Retrans. Vol (Bytes)` INT DEFAULT NULL, 
`TCP UL Retrans. Vol (Bytes)` INT DEFAULT NULL,
`HTTP DL (Bytes)` INT DEFAULT NULL, 
`HTTP UL (Bytes)` INT DEFAULT NULL, 
`Activity Duration DL (ms)` INT DEFAULT NULL,
`Activity Duration UL (ms)` INT DEFAULT NULL, 
`Dur. (ms).1` INT DEFAULT NULL, 
`Handset Manufacturer` TEXT DEFAULT NULL,
`Handset Type` TEXT DEFAULT NULL, 
`Social Media DL (Bytes)` INT DEFAULT NULL, 
`Social Media UL (Bytes)` INT DEFAULT NULL,
`Google DL (Bytes)` INT DEFAULT NULL, 
`Google UL (Bytes)` INT DEFAULT NULL, 
`Email DL (Bytes)` INT DEFAULT NULL,
`Email UL (Bytes)` INT DEFAULT NULL, 
`Youtube DL (Bytes)` INT DEFAULT NULL, 
`Youtube UL (Bytes)` INT DEFAULT NULL,
`Netflix DL (Bytes)` INT DEFAULT NULL, 
`Netflix UL (Bytes)` INT DEFAULT NULL, 
`Gaming DL (Bytes)` INT DEFAULT NULL,
`Gaming UL (Bytes)` INT DEFAULT NULL, 
`Other DL (Bytes)` INT DEFAULT NULL, 
`Other UL (Bytes)` INT DEFAULT NULL,
`Total UL (Bytes)` INT DEFAULT NULL, 
`Total DL (Bytes)` INT DEFAULT NULL, 
PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;